export type TrainingDataItem = {
  text: string
  label: string
}

export const trainingData = [
  { text: 'The new iPhone 15 Pro Max has an amazing camera!', label: 'tech' },
  { text: 'Just finished coding my first website using React!', label: 'tech' },
  {
    text: 'Artificial Intelligence is rapidly changing the world.',
    label: 'tech',
  },
  { text: "I'm excited about the future of self-driving cars.", label: 'tech' },
  { text: 'This new video game is so immersive and addictive!', label: 'tech' },
  { text: 'I love watching cooking shows on YouTube.', label: 'non-tech' },
  { text: 'My dog is the cutest thing ever!', label: 'non-tech' },
  {
    text: 'Going for a hike in the mountains this weekend.',
    label: 'non-tech',
  },
  { text: 'Reading a great book about history.', label: 'non-tech' },
  {
    text: "Can't wait for the next season of my favorite TV show.",
    label: 'non-tech',
  },
  { text: 'The new iPhone 15 Pro Max has an amazing camera!', label: 'tech' },
  { text: 'Just finished coding my first website using React!', label: 'tech' },
  {
    text: 'Artificial Intelligence is rapidly changing the world.',
    label: 'tech',
  },
  { text: "I'm excited about the future of self-driving cars.", label: 'tech' },
  { text: 'This new video game is so immersive and addictive!', label: 'tech' },
  { text: 'I love watching cooking shows on YouTube.', label: 'non-tech' },
  { text: 'My dog is the cutest thing ever!', label: 'non-tech' },
  {
    text: 'Going for a hike in the mountains this weekend.',
    label: 'non-tech',
  },
  { text: 'Reading a great book about history.', label: 'non-tech' },
  {
    text: "Can't wait for the next season of my favorite TV show.",
    label: 'non-tech',
  },
  {
    text: "Upgraded my PC with a new graphics card. Can't wait to play some games!",
    label: 'tech',
  },
  { text: 'Anyone else obsessed with the new OnePlus phone?', label: 'tech' },
  { text: 'Learning Python is challenging but rewarding.', label: 'tech' },
  { text: 'Just got back from a fantastic concert!', label: 'non-tech' },
  { text: 'Had the best sushi last night!', label: 'non-tech' },
  {
    text: 'Feeling grateful for all the amazing people in my life.',
    label: 'non-tech',
  },
  { text: "Can't believe how fast technology is advancing!", label: 'tech' },
  {
    text: "Building a robot arm with Arduino. It's coming along nicely!",
    label: 'tech',
  },
  { text: "My cat is so lazy, it's hilarious.", label: 'non-tech' },
  {
    text: 'Anyone else excited about the upcoming SpaceX launch?',
    label: 'tech',
  },
  { text: 'JavaScript is my go-to programming language.', label: 'tech' },
  { text: 'The latest Tesla model is a game-changer.', label: 'tech' },
  {
    text: "Just binge-watched the entire season of 'Squid Game.'",
    label: 'non-tech',
  },
  { text: 'Spending the day at the beach with friends.', label: 'non-tech' },
  { text: 'Trying out a new recipe for dinner tonight.', label: 'non-tech' },
  { text: 'Virtual reality is the next big thing.', label: 'tech' },
  { text: 'Blockchain technology has so much potential.', label: 'tech' },
  { text: 'My new laptop is super fast!', label: 'tech' },
  { text: 'Just finished a great workout at the gym.', label: 'non-tech' },
  { text: 'Love listening to podcasts on my commute.', label: 'non-tech' },
  { text: 'The graphics in this game are incredible!', label: 'tech' },
  { text: "Can't wait to see the new Marvel movie.", label: 'non-tech' },
  { text: 'Coding is my passion.', label: 'tech' },
  { text: "Google's new AI features are mind-blowing.", label: 'tech' },
  { text: 'Had a delicious brunch with my family.', label: 'non-tech' },
  { text: 'Dreaming of traveling the world someday.', label: 'non-tech' },
  { text: 'The internet is such a powerful tool.', label: 'tech' },
  { text: 'Cybersecurity is more important than ever.', label: 'tech' },
  { text: 'Just bought a new pair of shoes.', label: 'non-tech' },
  { text: 'Feeling stressed about work.', label: 'non-tech' },
  { text: 'The possibilities of 3D printing are endless.', label: 'tech' },
  { text: 'Love spending time with my family.', label: 'non-tech' },
  {
    text: 'Machine learning is revolutionizing many industries.',
    label: 'tech',
  },
  { text: 'Excited to try out the new PlayStation 5.', label: 'tech' },
  { text: 'Going to a music festival this summer.', label: 'non-tech' },
  { text: "Feeling inspired by nature's beauty.", label: 'non-tech' },
  { text: 'The metaverse is the future of social interaction.', label: 'tech' },
  { text: 'Quantum computing is mind-boggling.', label: 'tech' },
  { text: 'Just had a great conversation with a friend.', label: 'non-tech' },
  { text: 'Learning a new language is so challenging.', label: 'non-tech' },
  { text: 'The latest tech gadgets are amazing.', label: 'tech' },
  { text: 'Enjoying a quiet evening at home.', label: 'non-tech' },
  { text: 'Open source software is the way to go.', label: 'tech' },
  { text: 'The new MacBook Pro is a beast.', label: 'tech' },
  { text: 'Going to a yoga class later today.', label: 'non-tech' },
  { text: "Can't wait to see what the future holds.", label: 'non-tech' },
  { text: 'Data science is a fascinating field.', label: 'tech' },
  { text: 'The cloud is changing the way we store data.', label: 'tech' },
  { text: 'Just finished a delicious meal.', label: 'non-tech' },
  { text: 'Feeling happy and content.', label: 'non-tech' },
  { text: 'The advancements in robotics are incredible.', label: 'tech' },
  { text: 'Love exploring new places.', label: 'non-tech' },
  { text: 'The internet of things is connecting everything.', label: 'tech' },
  { text: 'Coding is like solving a puzzle.', label: 'tech' },
  { text: 'My favorite hobby is photography.', label: 'non-tech' },
  {
    text: 'Artificial intelligence is both exciting and scary.',
    label: 'tech',
  },
  {
    text: 'Spending quality time with loved ones is important.',
    label: 'non-tech',
  },
  { text: 'The new Samsung Galaxy phone looks impressive.', label: 'tech' },
  { text: 'Just finished a great book.', label: 'non-tech' },
  { text: 'The power of social media is undeniable.', label: 'tech' },
  { text: 'Enjoying a cup of coffee on a rainy day.', label: 'non-tech' },
  { text: 'The future of work is remote.', label: 'tech' },
  { text: 'Learning to play the guitar is my new goal.', label: 'non-tech' },
  {
    text: 'The possibilities of augmented reality are endless.',
    label: 'tech',
  },
  { text: 'Feeling inspired by art and creativity.', label: 'non-tech' },
  { text: 'The world of technology is constantly evolving.', label: 'tech' },
  { text: 'Just had a good laugh with my friends.', label: 'non-tech' },
  {
    text: 'The importance of mental health cannot be overstated.',
    label: 'non-tech',
  },
  { text: 'Excited about the new features in iOS 16.', label: 'tech' },
  {
    text: 'Taking a break from technology to enjoy nature.',
    label: 'non-tech',
  },
  { text: 'The impact of climate change is alarming.', label: 'non-tech' },
  { text: 'The beauty of the ocean is breathtaking.', label: 'non-tech' },
  { text: 'The advancements in medicine are remarkable.', label: 'tech' },
  { text: 'Feeling hopeful for the future.', label: 'non-tech' },
  { text: 'The world is full of wonders.', label: 'non-tech' },
  { text: 'Technology is making the world a smaller place.', label: 'tech' },
  { text: 'The human brain is a marvel of nature.', label: 'non-tech' },
  {
    text: 'The importance of education cannot be underestimated.',
    label: 'non-tech',
  },
  { text: 'The internet has revolutionized communication.', label: 'tech' },
  { text: 'The power of music to move us is incredible.', label: 'non-tech' },
  { text: 'The universe is vast and mysterious.', label: 'non-tech' },
  { text: 'Technology is shaping the future of our planet.', label: 'tech' },
  {
    text: 'The kindness of strangers restores my faith in humanity.',
    label: 'non-tech',
  },
]
